- CMakeLists.txt
- resources/gui/loading_screen.html
- src/cs-core/GuiManager.cpp
- src/cs-core/cs-version.hpp.in
> Display the most recent git tag, branch and commit on the loading screen

- README.md
- docs/README.md
- docs/changelog.md
> Add a changelog

- make_debug.bat
- make_debug.sh
- make_externals.sh
- make_release.bat
- make_release.sh
> :memo: Fix typos in make scripts

- config/base/CMakeLists.txt
- config/base/scripts/start.bat
- config/base/scripts/vive.bat
> Better windows start script

- .github/workflows/build.yml
- CMakeLists.txt
- README.md
- config/base/CMakeLists.txt
- config/base/scripts/run_graphical_tests.sh
- config/base/scripts/run_tests.bat
- config/base/scripts/run_tests.sh
- config/base/vista/vista_test.ini
- docs/ide-setup.md
- lcov.sh
- make.sh
- src/cosmoscout/main.cpp
- src/cs-utils/TestImageCompare.cpp
- src/cs-utils/TestImageCompare.hpp
- src/cs-utils/filesystem.cpp
- src/cs-utils/utils.cpp
- src/cs-utils/utils.hpp
This requires https://github.com/cosmoscout/csp-atmospheres/pull/4 to be merged.
> Add support for graphical unit tests

- src/cs-core/SolarSystem.cpp
- src/cs-core/SolarSystem.hpp
- src/cs-utils/FrameTimings.hpp
> Fix speed display

- CMakeLists.txt
- src/cosmoscout/Application.cpp
- src/cosmoscout/GetSelectionStateNode.cpp
- src/cs-core/DragNavigation.cpp
- src/cs-core/GraphicsEngine.cpp
- src/cs-core/GuiManager.cpp
- src/cs-core/GuiManager.hpp
- src/cs-core/InputManager.cpp
- src/cs-core/InputManager.hpp
- src/cs-core/Settings.hpp
- src/cs-core/SolarSystem.cpp
- src/cs-core/tools/Mark.cpp
- src/cs-graphics/ColorMap.cpp
- src/cs-graphics/Shadows.cpp
- src/cs-graphics/TextureLoader.cpp
- src/cs-graphics/ToneMappingNode.cpp
- src/cs-graphics/internal/tiny_gltf_helper.hpp
- src/cs-gui/ScreenSpaceGuiArea.hpp
- src/cs-gui/WebView.cpp
- src/cs-gui/WebView.hpp
- src/cs-gui/internal/WebViewClient.cpp
- src/cs-scene/CelestialObject.hpp
- src/cs-scene/Trajectory.cpp
- src/cs-scene/Trajectory.hpp
- src/cs-utils/FrameTimings.cpp
- src/cs-utils/Property.hpp
- src/cs-utils/TestImageCompare.cpp
This allows for `-Wall` and `-Werror`.
* https://github.com/cosmoscout/csp-atmospheres/pull/11
* https://github.com/cosmoscout/csp-anchor-labels/pull/7
* https://github.com/cosmoscout/csp-lod-bodies/pull/15
* https://github.com/cosmoscout/csp-rings/pull/7
* https://github.com/cosmoscout/csp-sharad/pull/10
* https://github.com/cosmoscout/csp-simple-bodies/pull/10
* https://github.com/cosmoscout/csp-measurement-tools/pull/9
> Remove all -Wall gcc warnings

- src/cosmoscout/Application.cpp
This fixes https://github.com/cosmoscout/cosmoscout-vr/issues/136, reduces the number of SPICE calls and fixes the sun-direction-one-frame-behind-issue.
> Fix update delay

- config/base/vista/display.ini
- src/cs-core/GraphicsEngine.cpp
- src/cs-core/tools/Mark.cpp
- src/cs-graphics/GlowMipMap.cpp
- src/cs-graphics/GlowMipMap.hpp
- src/cs-graphics/HDRBuffer.cpp
- src/cs-graphics/HDRBuffer.hpp
- src/cs-graphics/LuminanceMipMap.cpp
- src/cs-graphics/LuminanceMipMap.hpp
- src/cs-graphics/ToneMappingNode.cpp
- src/cs-utils/utils.hpp
With these fixes, we can enable multisampling in HDR mode.
> Fix multisample

- resources/gui/cosmoscout.html
- resources/gui/css/timeline.css
- resources/gui/js/apis/timeline.js
Redrawing the overview-lens was a very costly operation. It is now handled by the vis-timeline library itself.
> Improve timeline style and performance

- plugins/csp-minimap/gui/css/csp-minimap.css
- resources/gui/cosmoscout.html
- resources/gui/css/gui.css
- resources/gui/css/logo.css
- resources/gui/css/sidebar.css
- resources/gui/css/timeline.css
This makes the sidebar animations more fluent and adds some consistency by styling windows, sidebar and timeline more similar. It's a little more playful, but I actually like it. What do you think?
> Make windows and sidebar style more consistent

- plugins/csp-lod-bodies/gui/lod_body_tab.html
- resources/gui/css/gui.css
- resources/gui/js/apis/gui.js
This fixes #132 and tweaks the dropdown styling. It also adds an ever-so-slightly border radius to buttons.
> Fix dropdown styling

- plugins/csp-lod-bodies/shaders/VistaPlanetTerrainShaderFunctions.vert
- plugins/csp-lod-bodies/src/Plugin.cpp
- plugins/csp-lod-bodies/src/VistaPlanet.cpp
This does three things:
* Fix a crash when an invalid wms-dataset is given in the settings
* Slightly improve vertex position and normal calculation for lod-bodies
* Use correct matrices for shadow frustum culling
> Improve Lighting

- resources/gui/js/apis/gui.js
> :beetle: Prevent loosing draggable windows offscreen

- docs/ide-setup.md
Updates the documentation on CLion.
> Update CLion documentation.

- .gitmodules
- config/base/scene/simple_vive.json
- make.bat
- make_externals.bat
See https://github.com/cosmoscout/vista/pull/10.
> :beetle: Fix Vive support.

- make_externals.sh
- plugins/csp-lod-bodies/gui/lod_body_settings.html
- plugins/csp-lod-bodies/shaders/Planet.frag
- plugins/csp-lod-bodies/shaders/VistaPlanetTileBounds.frag
- plugins/csp-lod-bodies/src/LODVisitor.cpp
- plugins/csp-lod-bodies/src/LodBody.cpp
- plugins/csp-lod-bodies/src/PlanetShader.cpp
- plugins/csp-lod-bodies/src/Plugin.cpp
- plugins/csp-lod-bodies/src/Plugin.hpp
- plugins/csp-lod-bodies/src/TileRenderer.cpp
- plugins/csp-lod-bodies/src/TileRenderer.hpp
- plugins/csp-lod-bodies/src/VistaPlanet.cpp
- plugins/csp-sharad/src/Sharad.cpp
- plugins/csp-sharad/src/Sharad.hpp
- resources/gui/js/apis/utils.js
Testing CosmoScout VR in our VR-Lab revealed several issues. This PR fixes them all together :smiley: 
* SHARAD uses ellipsoids now as well.
* The statusbar shows elevation values < 0.
* Terrain tiles are now culled correctly when being close to the surface.
* Terrain tile bounding boxes can now be shown.
> Various fixes

- CMakeLists.txt
- docs/changelog.md
I started drafting the changelog for 1.3.0. It's already quite a lot! What do you think? Did I miss something important?
> Initial changelog draft for v1.3.0

- plugins/csp-anchor-labels/src/AnchorLabel.cpp
- plugins/csp-measurement-tools/src/DipStrikeTool.cpp
- plugins/csp-measurement-tools/src/FlagTool.cpp
- plugins/csp-measurement-tools/src/PathTool.cpp
- plugins/csp-measurement-tools/src/PolygonTool.cpp
- plugins/csp-trajectories/src/Trajectory.cpp
- src/cosmoscout/Application.cpp
- src/cosmoscout/Application.hpp
- src/cs-core/DragNavigation.cpp
- src/cs-core/SolarSystem.cpp
- src/cs-core/SolarSystem.hpp
- src/cs-core/TimeControl.hpp
- src/cs-scene/CelestialAnchor.cpp
- src/cs-scene/CelestialAnchor.hpp
- src/cs-scene/CelestialObserver.cpp
- src/cs-scene/CelestialObserver.hpp
This fixes several SPICE-related crashes.
This fixes issue #102
> Catch most SPICE errors

- docs/README.md
- docs/changelog.md
- docs/citation.md
- docs/configuring.md
- docs/migration.md
> Add migration guide

- resources/gui/js/apis/gui.js
> Add more flexible initSlider functions to the GuiApi

- make_externals.bat
Fixes https://github.com/cosmoscout/cosmoscout-vr/issues/211.
> Fix windows debug build.

- docs/changelog.md
> Add Changelog

- plugins/csp-simple-bodies/src/SimpleBody.cpp
- src/cs-core/SolarSystem.cpp
- src/cs-core/SolarSystem.hpp
This adds a convenience method to get Sun's luminance.
> Luminance getter

- plugins/csp-wms-overlays/src/Plugin.cpp
- src/cosmoscout/Application.cpp
- src/cs-core/Settings.cpp
- src/cs-core/Settings.hpp
- src/cs-core/TimeControl.cpp
- src/cs-core/TimeControl.hpp
This saves and loads the time speed to and from the config files.
> Save time speed

- plugins/csp-lod-bodies/src/PlanetShader.cpp
- plugins/csp-wms-overlays/src/Plugin.cpp
This fixes some compilation issues on gcc 11.
> GCC 11 fixes

- plugins/csp-lod-bodies/shaders/Planet.frag
- plugins/csp-lod-bodies/shaders/Planet.vert
- plugins/csp-lod-bodies/shaders/VistaPlanetTerrainShaderFunctions.vert
- plugins/csp-lod-bodies/shaders/VistaPlanetTerrainShaderUniforms.glsl
- plugins/csp-lod-bodies/src/TileRenderer.cpp
- plugins/csp-lod-bodies/src/TileRenderer.hpp
- plugins/csp-lod-bodies/src/VistaPlanet.cpp
- plugins/csp-lod-bodies/src/VistaPlanet.hpp
- plugins/csp-rings/src/Ring.cpp
- plugins/csp-rings/src/Ring.hpp
- plugins/csp-simple-bodies/src/SimpleBody.cpp
- plugins/csp-simple-bodies/src/SimpleBody.hpp
This fixes some lighting and eclipse shadow issues in VR.
> Perform lighting computation in world space

- plugins/csp-trajectories/src/SunFlare.cpp
> Fix draw order of Sun Flare

- plugins/csp-rings/src/Ring.cpp
- plugins/csp-rings/src/Ring.hpp
Rings have now shading on the dark side based on transparency:
> Ring self shadowing

- .github/workflows/build.yml
- README.md
- docs/changelog.md
- docs/continuous-integration.md
- docs/contributing.md
- docs/install.md
- docs/release-management.md
- plugins/csp-web-api/gui/example-web-frontend.html
I hope that I got everything...
> Update all references to "master" and "develop" by "main"

- docs/configuring.md
> Update vista links

- docs/changelog.md
- plugins/csp-atmospheres/src/AtmosphereRenderer.cpp
- plugins/csp-stars/src/Plugin.cpp
- plugins/csp-stars/src/Shaders.cpp
- plugins/csp-stars/src/Stars.cpp
- plugins/csp-stars/src/Stars.hpp
This disables star drawing when the observer is on the day-side of a planet with an atmosphere. Also, the star position is now computed on the GPU.
> Stars optimization

- plugins/csp-lod-bodies/src/TileSourceWebMapService.cpp
> fix contentType check

- docs/changelog.md
- src/cs-core/SolarSystem.cpp
The direction of the sunlight wasn't updated properly after a scene got reloaded.
> Fix fixed Sun direction after scene loading

- docs/changelog.md
- resources/gui/cosmoscout.html
- resources/gui/js/apis/timeline.js
This allows to adjust the simulation time in a continuous manner.
> Make it possible to adjust the time speed continuously

- docs/changelog.md
- plugins/csp-stars/src/Stars.cpp
This fixes loading of stars from the Hipparcos catalog which do not have Tycho photometry.
> Fix star loading

- plugins/csp-lod-bodies/src/TileSourceWebMapService.cpp
- src/cs-core/GraphicsEngine.cpp
I couldn't compile CosmoScout with VS2022, due to multiple reasons. I updated OpenSG and spdlog and follow up errors in CosmoScout VR.
> Fix Visual Studio 2022 compilation
