cosmoscout/cosmoscout-vr

- src/cs-graphics/LuminanceMipMap.cpp
- src/cs-graphics/internal/pbr_fragment_shader.hpp
Unbind pbo after usage in LuminanceMipMap constructor and fix type of a uniform variable in the gltf fragment shader.
> :beetle: Fix two small GL bugs

- src/cosmoscout/CMakeLists.txt
- src/cosmoscout/icon.rc
This adds an icon to the cosmoscout executable and to the glut window on Windows. For Linux, this is more involved...
> Add icon to executable and window on Windows

- src/cs-gui/ScreenSpaceGuiArea.cpp
- src/cs-gui/ScreenSpaceGuiArea.hpp
This "fixes" the occasional issue of of a wrongly resized gui. It's rather a workaround than a fix, but it does the trick and might actual increase the framerate during window resizing.
> Fix wrongly resized gui by waiting some frames

- make_externals.bat
- make_externals.sh
CMake 3.17 changed the `FindCURL.cmake` script. This broke our build of curlpp. This merge request fixes this.
This fixes issue #134.
> Fix a bug in the build_externals intruduced with CMake 3.17

- .github/workflows/build.yml
- make_externals.bat
- make_externals.sh
Requires: 
- https://github.com/cosmoscout/opensg-1.8/pull/1
- https://github.com/cosmoscout/vista/pull/3
If the current CMAKE_VERSION is at least 3.16 unity builds and precompiled headers will be used. This reduced the OpenSG compile time on Windows from 15 Minutes to 2 Minutes on my machine.
> Fast build

- cmake/FindTIFF.cmake
- make_externals.bat
- src/cosmoscout/Application.cpp
- src/cosmoscout/Application.hpp
- src/cosmoscout/main.cpp
- src/cs-core/Settings.cpp
- src/cs-core/Settings.hpp
- src/cs-utils/CMakeLists.txt
This adds the following features:
* Save and load the scene from and to a json string (instead of a json file).
* A `/save` and a `/load` endpoint for `csp-web-api` which allows, well, saving and loading of the scene via http.
* A `&depth=true|false` parameter to the /capture endpoint of `csp-web-api` to allow capturing of 32 bit tiff depth images.
I forgot to create a feature branch for `csp-web-api`, here's the diff: https://github.com/cosmoscout/csp-web-api/compare/259f00b28e26009bb6f7ffc78ece7fbeb7ca3b89...develop
> Capture Depth Images

- resources/gui/cosmoscout.html
- resources/gui/css/calendar.css
- resources/gui/css/gui.css
With the class `.auto-hide-header` window title bars can now be hidden automatically. This reduces screen clutter and is currently used for the calendar and will be used for the minimap soon. The title bar is revealed when the pointer is above the window.
In `cosmoscout.html` actually only four lines changed because a `<div class="window-wrapper">` was added. The rest is indentation. :open_mouth:
> Add possibiltity to auto-hide window headers

- docs/install.md
- make.bat
- make_externals.bat
This pull request aims to improve build times on windows by making the `make_externals.bat` compatible with the Ninja generator.
Here are some measurements on build times:
```
.\make_externals.bat -GNinja -DCMAKE_C_COMPILER=cl.exe -DCMAKE_CXX_COMPILER=cl.exe
Ninja Clean: 06:08 (mm:ss)
Ninja NOOP:  02:07 (mm:ss)
----------------------------------------------------------------------------------
.\make_externals.bat -G "Visual Studio 16 2019" -A x64
MSBuild Clean: 10:52 (mm:ss)
MSBuild NOOP:  02:44 (mm:ss)
```
Both compilations were done from the `x64 Native Tools Command Prompt for VS 2019`.
I will also add some documentation. Before this is ready to merge.
> :wrench: make_externals.bat now works with Ninja as a generator.

- src/cosmoscout/Application.cpp
- src/cs-core/Settings.cpp
- src/cs-core/Settings.hpp
- src/cs-core/SolarSystem.cpp
This adds the possibility to create artificial lighting conditions. This is for example required to generate training data for crater detection.
This will make all bodies be lit from their south pole:
```javascript
CosmoScout.callbacks.graphics.setFixedSunDirection(0, -1, 0)
```
Use this to disable the feature again:
```javascript
CosmoScout.callbacks.graphics.setFixedSunDirection(0, 0, 0)
```
> Add possibility to specify a fixed sun direction

- src/cs-scene/CelestialObserver.cpp
Even if the animation time was set to zero, it took one frame to update the observer's position and rotation. Hence multiple calls to CelestialObserver::moveTo would "overwrite" each other.
Calling something like this didn't work (but does now):
```javascript
CosmoScout.callbacks.navigation.setPosition(x, y, z, 0);
CosmoScout.callbacks.navigation.setRotation(x, y, z, w, 0);
```
> Allow multiples calls to CelestialObserver::moveTo per frame

- plugins/csp-web-api/gui/example-web-frontend.html
- plugins/csp-web-api/src/Plugin.cpp
- plugins/csp-web-api/src/Plugin.hpp
This adds a `&format=png` (or `tiff` or `jpeg`) parameter to the `/capture` endpoint of `csp-web-api` which lets you capture depth and color images in different formats.
The main advantage is speed, since png or tiff images tend to be quite large.
> Add the possibilty to capture images in multiple formats

- make_externals.bat
This adds a `goto` label for each library in `make_exernals.bat`. This is primarily for fixing external build errors, so you can easily jump to the broken library and don't have to go through all previous build steps each time.
> Goto Labels for make_externals.bat

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- CMakeLists.txt
- clang-tidy.sh
- docs/continuous-integration.md
- docs/ide-setup.md
- docs/install.md
- lcov.sh
- make.bat
- make.sh
- make_externals.bat
- make_externals.sh
Capitalize build types names. I did this to simplify integration of the vscode-cmake-tools addon in my vscode setup.
> :wrench: Capitalize build types to match CMake and VS conventions

- README.md
- cloc.sh
As we have quite a lot of JavaScript code, we should include it in out LoC / Comment Percentage calculations. This PR also fixes an error in the calculation (the copyright header was subtracted as five lines but it's actually only three lines).
> Update LoC count

- plugins/csp-lod-bodies/README.md
This adds an initial tutorial on how-to setup the MapServer on Ubuntu 20.04 (maybe also 18.04). It would be great if someone could verify that this works as supposed!
> MapServer Documentation

- make_externals.bat
- make_externals.sh
I replaced the `Invoke-WebRequest` commands on windows with `curl.exe` commands, which reduces download times by a few minutes.
Unzipping of CSpice now only extracts the relevant folders.
> Faster builds

- plugins/csp-anchor-labels/src/logger.cpp
- plugins/csp-anchor-labels/src/logger.hpp
- plugins/csp-fly-to-locations/src/logger.hpp
- plugins/csp-lod-bodies/src/logger.cpp
- plugins/csp-lod-bodies/src/logger.hpp
- plugins/csp-measurement-tools/src/logger.cpp
- plugins/csp-measurement-tools/src/logger.hpp
- plugins/csp-simple-bodies/src/logger.cpp
- plugins/csp-simple-bodies/src/logger.hpp
This makes our logger names more consistent. They now should always use the plugin name.
> Consistent logger names

- src/cs-graphics/HDRBuffer.hpp
- src/cs-gui/types.hpp
With this, CosmoScout VR compiles fine for me on Ubuntu 20.04 with gcc 9.3.0, 10.0.1 and 10.2.0. This should resolve #185.
> Add some includes for gcc 10.2.0

- resources/gui/css/statusbar.css
- resources/gui/js/apis/statusbar.js
This makes the JavaScript console auto-complete to the longest shared prefix if there are multiple matches. It also makes sure that the suggestions are shown above the sidebar, making them always clickable.
> Console fixes

- plugins/csp-lod-bodies/README.md
- plugins/csp-lod-bodies/shaders/VistaPlanetTerrainShaderFunctions.frag
- plugins/csp-lod-bodies/src/TileSourceWebMapService.cpp
- plugins/csp-lod-bodies/src/TileSourceWebMapService.hpp
This adds the following:
* `"url": "offline"` can now be used to prevent a `TileSourceWebMapService` from accessing a map server. Only cached data will be used.
* The terrain shader works with OpenGL 3.3.
* If loading of a cached tile fails, it will be removed now effectively triggering a re-download.
* `csp-lod-bodies` will now only print errors for critical events. If downloading a tile failed, this not considered critical.
* The slope-range and height-range slider now work as supposed.
> LOD body fixes

- docs/configuring.md
- plugins/csp-trajectories/src/Trajectory.cpp
- plugins/csp-trajectories/src/Trajectory.hpp
This fixes issue #102 by not attempting to draw a trajectory when the target body is not in existence.
This PR also updates Vista to the current develop branch.
> Fix SPICE crash

- plugins/csp-stars/src/Stars.cpp
- src/cs-utils/utils.cpp
Replaced the string split method in utils with a faster one. The stars plugin now makes use of it. It reduced inital loading times from 20 to 15 seconds.
> Faster loading of stars on initial startup

- plugins/csp-atmospheres/src/Plugin.cpp
The enable-light-shafts-checkbox of the `csp-atmospheres` plugin behaved like it was inverted. The reason was that the `onChange` signals get emitted _before_ the internal value is changed.
> Fix inverted light shaft condition

- plugins/csp-simple-bodies/src/SimpleBody.cpp
- src/cs-core/SolarSystem.cpp
After studying [_"Reference luminous solar constant and solar luminance for illuminance calculations." by Darula, Stan, Richard Kittler, and Christian A. Gueymard_](http://www.academia.edu/download/50238350/Reference_luminous_solar_constant_and_so20161110-7287-1ipdcez.pdf), I realized that our luminance calculation for the Sun was still not right. This should fix it now.
> Fix luminance calculation for the Sun

- plugins/csp-atmospheres/src/Shaders.cpp
- plugins/csp-lod-bodies/shaders/Planet.frag
- plugins/csp-rings/src/Ring.cpp
- plugins/csp-rings/src/Ring.hpp
- plugins/csp-simple-bodies/src/SimpleBody.cpp
In HDR rendering, we are missing a division by π to be ernergy-conserving for Lambertian surfaces. See https://seblagarde.wordpress.com/2012/01/08/pi-or-not-to-pi-in-game-lighting-equation/ for an explanation.
The brightness of the clouds in HDR mode is still quite arbitrary. This needs to be fixed in the future.
> Fix energy conservation in shading

- src/cs-utils/Signal.hpp
- test/cs-utils/Signal.cpp
Added safeguards, that prevent a crash, when a slot is disconnected while the signal is emitting all its slots.
The slots that are disconnected while emitting will be stored and disconnected after all other slots have been called.
> Safer Signals and Slots

- plugins/csp-atmospheres/src/AtmosphereRenderer.cpp
- plugins/csp-lod-bodies/src/Plugin.cpp
- plugins/csp-stars/src/Stars.cpp
- plugins/csp-timings/README.md
- plugins/csp-timings/gui/css/timings.css
- plugins/csp-timings/gui/js/csp-timings.js
- plugins/csp-timings/gui/timings.html
- plugins/csp-timings/src/Plugin.cpp
- plugins/csp-timings/src/Plugin.hpp
- src/cosmoscout/Application.cpp
- src/cosmoscout/Application.hpp
- src/cs-core/GuiManager.cpp
- src/cs-core/GuiManager.hpp
- src/cs-core/PluginBase.cpp
- src/cs-core/PluginBase.hpp
- src/cs-core/SolarSystem.cpp
- src/cs-core/SolarSystem.hpp
- src/cs-graphics/GlareMipMap.cpp
- src/cs-graphics/LuminanceMipMap.cpp
- src/cs-graphics/ToneMappingNode.cpp
- src/cs-utils/FrameTimings.cpp
- src/cs-utils/FrameTimings.hpp
This PR significantly improves the frame timing capabilities of CosmoScout VR. Here are the changes:
* The `FrameTimings` now keep track of the number of currently active ranges. This allows us to determine the current nesting level of a timing range.
* The statistics UI element now shows the ranges as they were recorded for the last-but-one frame with the appropriate nesting level. There are tooltips for detailed information.
* A triple buffer is used for the timer queries, which improves performance.
* The recording-to-file has been adapted accordingly. It now creates a set of files, one for each nesting level per CPU or GPU.
* The `FrameTimings` class is now a real singleton, before it used some hidden static variables.
> Improved timings

- plugins/csp-fly-to-locations/src/Plugin.cpp
- plugins/csp-minimap/src/Plugin.cpp
- resources/gui/js/apis/bookmark_editor.js
- src/cosmoscout/Application.cpp
- src/cs-core/Settings.hpp
- src/cs-core/SolarSystem.cpp
This fixes the following:
* Bookmarks with orientation did not set the correct orientation.
* It wasn't possible to set bookmarks relative to the Solar System's Barycenter because Jupiter kept being the active body even if zoomed out very far.
> Bookmark fixes

- .gitmodules
- make_externals.bat
As it happens occasionally that https://gitlab.com/libtiff/libtiff is not available, our CI builds sometimes stop working all of a sudden. To prevent this, we should use a forked version of libtiff.
For existing clones of CosmoScout VR, this may require
```
git submodule sync --recursive
git submodule update
```
> Use forked version of libtiff

- resources/gui/cosmoscout.html
- src/cosmoscout/Application.cpp
- src/cs-core/GraphicsEngine.cpp
- src/cs-core/Settings.cpp
- src/cs-core/Settings.hpp
- src/cs-graphics/ToneMappingNode.cpp
- src/cs-graphics/ToneMappingNode.hpp
This adds the possibility to support multiple tonemapping modes. For now, Filmic and None are supported, but we could add more in the future.
In addition, this reorganizes the settings section of the sidebar a bit to only use two tabs for the graphics settings.
> Make tonemapping configurable

- CITATION.cff
This resolves #267. However, once the IEEE Aerospace paper is published, we should add this as the preferred publication for citing.
> Add initial CFF file

- docs/changelog.md
- plugins/csp-web-api/gui/example-web-frontend.html
- plugins/csp-web-api/src/Plugin.cpp
This fixes a regression which causes the depth images which can be captured with the  `csp-web-api` plugin not to be in meters anymore. This was caused by our changed projection matrix.
> Capture in meters

- .github/workflows/build.yml
- cmake/FindGLUT.cmake
> Use ccache for CI

- docs/changelog.md
- resources/gui/js/apis/statusbar.js
- resources/gui/js/apis/timeline.js
After some digging around I found out that the whole UI rerenders basically every frame, because the date-time and statusbar elements were rerendered every frame.
I added a simple check to avoid that from happening.
> :wrench: Avoid rerenders of unchanging elements.

- docs/changelog.md
- plugins/csp-lod-bodies/shaders/Planet.frag
- plugins/csp-lod-bodies/shaders/VistaPlanetTerrainShaderUniforms.glsl
- plugins/csp-lod-bodies/src/PlanetShader.cpp
- plugins/csp-lod-bodies/src/TileRenderer.cpp
- plugins/csp-simple-bodies/src/SimpleBody.cpp
- resources/gui/cosmoscout.html
- src/cosmoscout/Application.cpp
- src/cs-core/Settings.cpp
- src/cs-core/Settings.hpp
Changes:
* Added a new `ambientOcclusion` setting which for now controls the amount of artificial hill-shading on the terrain. Previously, this was hard-coded.
* Reduced some code duplication in the planet shader.
* The tile-borders of `csp-lod-bodies` can now also be visualized in HDR mode.
* Ambient lighting works again in HDR-mode,
* Ambient lighting is set to a more realistic value of zero per default.
* The mapping of the ambient-lighting slider now feels more linear (both in HDR and non-HDR mode).
* If ambient lighting is set to one, the terrain is not affect by the sun light direction anymore.
* The ambient lighting now properly interacts with eclipse shadows on simple bodies.
> Fix terrain lighting

- plugins/csp-atmospheres/shaders/csp-atmospheres/atmosphere.frag
- plugins/csp-atmospheres/shaders/csp-atmospheres/atmosphere.vert
- plugins/csp-simple-bodies/src/SimpleBody.cpp
When you use the `version 330` of atmospheres and simple-bodies shaders, you get the following errors:
```bash
GL_INVALID_OPERATION in glUniform(program not linked)
GL_INVALID_OPERATION in glUniformMatrix(program not linked)
**WARNING** Shader porgram with id 389 is not ready for use. Bind has no effect.
###ERROR### OpenGL  error 1282 (invalid operation)
```
The error was resolved by incrementing the versions of the atmospheres and simple-bodies shaders to `version 430`.
> Shader issue resolved

- config/base/scene/simple_desktop.json
- docs/changelog.md
- plugins/csp-lod-bodies/src/HEALPix.cpp
- plugins/csp-lod-bodies/src/HEALPix.hpp
- plugins/csp-lod-bodies/src/utils.cpp
- src/cosmoscout/ObserverNavigationNode.cpp
- src/cs-core/DragNavigation.cpp
- src/cs-core/DragNavigation.hpp
With this, we can load much more high-resolution data. Changes:
* Increased maximum HEALPix depth from 20 to 30. This reduces our minimum tile size from about 13 m to 13 mm.
* Improved the scene scaling of the default configuration to allow for a smoother navigation close to the surface.
* Fixed an issue which led to an accumulated error in the rotation quaternion of the observer.
* Fixed an issue which caused precision issues for very small movements of the click-and-drag navigation.
With this set of changes, we can go well beyond a 1:1 scene scale and actually explore map data "like an ant" in the sub-millimeter range.
> Increase maximum HEALPix depth

- docs/changelog.md
- src/cs-core/Settings.cpp
- src/cs-scene/CelestialObject.cpp
- src/cs-scene/CelestialObject.hpp
When saving the scene with `CosmoScout.callbacks.core.save(...)`, optional properties of the celestial objects are not written anymore. This also fixes a warning about the Barycenter having no radii when saving the scene.
> Fix celestial object saving

- plugins/csp-atmospheres/src/Plugin.cpp
The checkbox was not updated when moving between planets.
> Fix update of waves checkbox

- plugins/csl-node-editor/gui/csl-node-editor.html
- plugins/csl-node-editor/src/Node.hpp
- plugins/csl-node-editor/src/NodeEditor.cpp
- plugins/csl-node-editor/src/NodeFactory.cpp
- plugins/csl-node-editor/src/NodeFactory.hpp
- plugins/csp-demo-node-editor/CMakeLists.txt
- plugins/csp-demo-node-editor/src/Plugin.cpp
- plugins/csp-demo-node-editor/src/controls/TextDisplayControl.js
- plugins/csp-demo-node-editor/src/nodes/DisplayNode.js
- plugins/csp-demo-node-editor/src/nodes/TimeNode.cpp
- plugins/csp-demo-node-editor/src/nodes/TimeNode.hpp
- plugins/csp-demo-node-editor/src/nodes/TimeNode.js
This PR adds two new features to the csl-node-editor and implements them in the csp-demo-node-editor.
1. `csl::nodeeditor::Node` now has a virtual `init()` function which can be implemented to do some initialization directly after the node is in a valid state.
2. Add a function to the `csl::nodeditor::NodeFactory` to register `Rete.Control` sublcasses, so they can be reused by multiple nodes.
> Node Editor Improvements

- docs/changelog.md
- plugins/csp-lod-bodies/src/Plugin.cpp
This PR ensures that LoD bodies are properly re-registered as CelestialSurfaces after reloading the settings.
> Fix lod body loading

- config/base/vista/display.ini
- docs/changelog.md
This fixes rendering bugs caused by text rendering in vista and adds a font to the vista config by default.
> Enable vista text rendering

- docs/changelog.md
- src/cosmoscout/Application.cpp
Added a callback `CosmoScout.callbacks.input.reloadDFNs()` to hot reload DFN xml files.
You can easily test it by doing the following:
1. Start CosmoScout VR
2. Move around with "W A S D"
3. Change the keys in the "keyboard_navigation.xml" from "w a s d" to "i j k l"
4. Type `CosmoScout.callbacks.input.reloadDFNs()` into the JS console.
5. Try moving around with "I J K L", instead of "W A S D"
> Add callback for hot reloading DFNs

- src/cosmoscout/ObserverNavigationNode.cpp
- src/cosmoscout/ObserverNavigationNode.hpp
This adds a `fixed_horizon` parameter to the ObserNavigationNode. If this is set to `true`, the observer is always rotated so that the horizon of the active object is always leveled.
For now, this breaks if we are in outer space or looking straight up or down. But it can already be very useful in cases were we know that the user is always close to a planet.
In the future, we could try making this work in outer space as well by checking the distance to the active object and gradually transitioning to the fixed horizon based on the distance.
You can enable this in DFN like this:
```xml
<node name="observer" type="ObserverNavigationNode">
<param name="fixed_horizon" value="true" />
</node>
```
> Add fixed_horizon option to the ObserverNavigationNode

- docs/changelog.md
- src/cs-scene/Trajectory.cpp
Currently, we write depth for the first half of a trajectory line. This enables better draw-order compositing with other transparent objects but produces severe artifacts on some (non-Quadro?) GPUs.
This PR disables depth write for trajectories altogether. This improves rendering on many GPUs. Now, trajectory lines are now not always correctly composited with transparent objects, but this will be visible only in very rare cases.
Before | After
-------|------
A better (but significantly more complex) solution would be to draw the trajectories using triangles instead of the very fragile smoothed GL lines. But I think that this solution is a simple improvement for now.
> Disable depth-write for trajectories

- resources/shaders/glare.comp
- resources/shaders/glareComposite.comp
- resources/shaders/tonemap.frag
- src/cs-core/GraphicsEngine.cpp
- src/cs-graphics/CMakeLists.txt
- src/cs-graphics/GlareMipMap.cpp
- src/cs-graphics/GlareMipMap.hpp
- src/cs-graphics/HDRBuffer.cpp
- src/cs-graphics/HDRBuffer.hpp
This pull request implements a compute-shader-based bi-cubic glare-interpolation as a preprocessing step. Previously, the bi-cubic glare-interpolation was performed on-the-fly in the tonemapping pass which operates at window resolution granularity, although the glare-MipMaps are by default not computed at full resolution.
As a result of this pull-request, the combined processing time for computing glare-MipMap computation and Tonemapping pass in bi-cubic interpolation mode is reduced drastically (as an example: from ~1.3 ms down to ~0.7 ms using default Cosmoscout-VR settings on a Laptop equipped with an NVIDIA RTX 3070).
The first image shows an example of the old in-place bi-cubic interpolation performed **within the tonemapping pass**. The GPU execution time of the tonemapping pass …
> Evaluate Bi-Cubic Glare-Interpolation in Compute-Preprocess for

- plugins/csp-atmospheres/shaders/csp-atmosphere.frag
- plugins/csp-atmospheres/src/Atmosphere.cpp
Through the pacific ocean, there is a one-pixel wide line even if all GUI is disabled. The line only disappears when clouds are disabled.
On closer inspection it appears there are not one, but 10 lines
It is an issue with the sampling of the cloud texture at the line where u=1 and u=0 meet, similar to https://stackoverflow.com/questions/38357970/opengl-texture-repeat-artifacts.
I implemented the suggested solution of forcing a lower MAX_LOD, I found empirically, that at a maximum MipMap level of 5, the glitch reliably does not appear anymore.
Before I figured this out, I debugged the cloud rendering. Is there a reason for using one-parameter atan(y_over_x) with logic for handling the different cases, instead of using two-parameter atan(y, x). I changed this to two-parameter atan and still …
> 🪲 remove the line through the pacific

- plugins/csp-stars/src/Plugin.cpp
- plugins/csp-stars/src/Plugin.hpp
This ensures that the set magnitude limits are actually used initially. Also, the lower magnitude limit is reduced so that bright stars are not culled close to the camera.
> Fix initial star magnitude limits

- docs/changelog.md
- plugins/csp-atmospheres/shaders/csp-atmosphere.frag
This fixes an issue which caused some flickering above the horizon at nighttime if refraction was enabled and lighting was disabled.
Before | After
--- | ---
> Fix horizon flickering

- docs/changelog.md
- src/cs-core/GraphicsEngine.cpp
- src/cs-gui/GuiItem.cpp
- src/cs-gui/GuiItem.hpp
- src/cs-gui/ScreenSpaceGuiArea.cpp
- src/cs-gui/WorldSpaceGuiArea.cpp
This improves rendering performance on some systems by uploading GUI textures using a staging buffer instead of using persistently mapped buffers.
> Faster gui uploads

- plugins/csp-atmospheres/src/Atmosphere.cpp
- plugins/csp-atmospheres/src/Atmosphere.hpp
- plugins/csp-sharad/src/Plugin.cpp
- plugins/csp-sharad/src/Sharad.cpp
- plugins/csp-sharad/src/Sharad.hpp
- plugins/csp-wms-overlays/src/Plugin.cpp
- plugins/csp-wms-overlays/src/ShadersTextureOverlay.cpp
- plugins/csp-wms-overlays/src/TextureOverlayRenderer.cpp
- plugins/csp-wms-overlays/src/TextureOverlayRenderer.hpp
- src/cs-core/GraphicsEngine.cpp
- src/cs-core/GraphicsEngine.hpp
The number of times we copied the depth buffer per frame has increased quite significantly. Once per atmosphere, once per sharad profile, once per WMS overlay. Soon I want to render some decals which will also require access to the depth buffer.
This PR adds a method to the `GraphicsEngine` which allows binding the current depth and color targets of the framebuffer as textures.
I have tested this with multiple viewports, but not in stereo.
> Less depth buffer copies
